export const branding = {
  productName: "IDP HR",
  workspaceTitle: "Кабинет",
  loadingWorkspace: "Загружаем рабочее пространство…",
  openMenu: "Открыть меню",
  closeMenu: "Закрыть меню",
  menuTitle: "Основное меню",
  logout: "Выйти",
  loginTitle: "Вход в аккаунт",
  emailLabel: "Email",
  passwordLabel: "Пароль",
  loginButton: "Войти",
  submitting: "Подождите…",
  loginError: "Не удалось выполнить вход",
  vacanciesTitle: "Вакансии",
  filtersTitle: "Фильтры",
  titleFilterLabel: "Название",
  titleFilterPlaceholder: "Поиск по названию",
  resetFilters: "Сбросить",
  filterEmpty: "По заданному названию вакансии не найдены",
  totalLabel: "Всего",
  externalId: "ID HH",
  vacancyName: "Вакансия",
  companyName: "Компания",
  hhLinkColumn: "Ссылка на HH.RU",
  vacanciesLoading: "Загружаем вакансии…",
  vacanciesError: "Не удалось загрузить вакансии",
  vacanciesEmptyTitle: "Вакансии не синхронизированы",
  vacanciesEmptyDescription: "Здесь появятся ваши вакансии после синхронизации.",
  dateMissing: "Дата не указана",
  publishedAt: "Опубликована",
  syncedAt: "Синхронизирована",
  openVacancy: "↗",
  openVacancyLabel: "Открыть вакансию на HH.RU",
} as const;
