export const branding = {
  productName: "Fezzyvig",
  workspaceTitle: "Рабочее пространство",
  loadingWorkspace: "Загружаем рабочее пространство…",
  openMenu: "Открыть меню",
  closeMenu: "Закрыть меню",
  menuTitle: "Основное меню",
  logout: "Выйти",
  loginTitle: "Вход в аккаунт",
  emailLabel: "Email",
  passwordLabel: "Пароль",
  loginButton: "Войти",
  submitting: "Подождите…",
  loginError: "Не удалось выполнить вход",
  vacanciesTitle: "Мои вакансии",
  connectionTitle: "Подключение HeadHunter",
  connectionDescription: "Подключите кабинет работодателя и синхронизируйте опубликованные вакансии.",
  connectButton: "Подключить HH ↗",
  syncButton: "Синхронизировать",
  syncing: "Синхронизация…",
  syncingMessage: "Синхронизируем вакансии с HeadHunter…",
  syncedMessage: "Синхронизировано вакансий",
  syncError: "Не удалось синхронизировать вакансии",
  vacanciesLoading: "Загружаем вакансии…",
  vacanciesError: "Не удалось загрузить вакансии",
  vacanciesEmptyTitle: "Вакансии не синхронизированы",
  vacanciesEmptyDescription: "Подключите кабинет HeadHunter и запустите синхронизацию.",
  dateMissing: "Дата не указана",
  publishedAt: "Опубликована",
  syncedAt: "Синхронизирована",
  descriptionMissing: "Описание отсутствует.",
  openVacancy: "Открыть на HH ↗",
} as const;
