export const branding = {
  productName: "IDP HR",
  workspaceTitle: "Кабинет",
  loadingWorkspace: "Загружаем рабочее пространство…",
  openMenu: "Открыть меню",
  closeMenu: "Закрыть меню",
  menuTitle: "Основное меню",
  synchronize: "Синхронизировать",
  syncQueued: "Синхронизация поставлена в очередь…",
  syncRunning: "Синхронизация выполняется…",
  syncComplete: "Синхронизировано вакансий",
  syncFailed: "Не удалось синхронизировать вакансии",
  logout: "Выйти",
  loginTitle: "Вход в аккаунт",
  emailLabel: "Email",
  passwordLabel: "Пароль",
  loginButton: "Войти",
  submitting: "Подождите…",
  loginError: "Не удалось выполнить вход",
  vacanciesTitle: "Вакансии",
  vacanciesSubtitle: "Синхронизированные вакансии работодателя",
  filtersTitle: "Фильтры",
  titleFilterLabel: "Название",
  titleFilterPlaceholder: "Поиск по названию",
  resetFilters: "Сбросить",
  filterEmpty: "По заданному названию вакансии не найдены",
  totalLabel: "Всего",
  externalId: "ID HH",
  vacancyName: "Вакансия",
  vacancyDetails: "Карточка вакансии",
  backToVacancies: "← К списку вакансий",
  vacancyNotFound: "Вакансия не найдена",
  vacancySummary: "Основные данные",
  areaName: "Регион",
  employmentForm: "Форма занятости",
  vacancyType: "Тип вакансии",
  createdAt: "Создана",
  expiresAt: "Срок публикации истекает",
  description: "Описание",
  hhData: "Данные HeadHunter",
  noHhData: "Данные HeadHunter пока отсутствуют",
  companyName: "Компания",
  hhLinkColumn: "Ссылка на HH.RU",
  vacanciesLoading: "Загружаем вакансии…",
  vacanciesError: "Не удалось загрузить вакансии",
  vacanciesEmptyTitle: "Вакансии не синхронизированы",
  vacanciesEmptyDescription: "Здесь появятся ваши вакансии после синхронизации.",
  dateMissing: "Дата не указана",
  publishedAt: "Опубликована",
  syncedAt: "Синхронизирована",
  openVacancy: "↗",
  openVacancyLabel: "Открыть вакансию на HH.RU",
} as const;
