export const hhVacancyFieldLabels: Record<string, string> = {
  "found": "Всего вакансий в ответе",
  "items": "Вакансии",
  "page": "Страница",
  "pages": "Всего страниц",
  "per_page": "Вакансий на странице",
  "id": "ID вакансии",
  "premium": "Премиум",
  "name": "Название",
  "has_test": "Есть тест",
  "response_letter_required": "Требуется сопроводительное письмо",
  "response_url": "Ссылка для отклика",
  "sort_point_distance": "Расстояние для сортировки",
  "archived": "В архиве",
  "expires_at": "Срок публикации истекает",
  "can_upgrade_billing_type": "Можно повысить тип продвижения",
  "salary": "Зарплата",
  "salary_range": "Диапазон зарплаты",
  "type": "Тип вакансии",
  "type.id": "Код типа вакансии",
  "type.name": "Название типа вакансии",
  "employment_form": "Форма занятости",
  "employment_form.id": "Код формы занятости",
  "employment_form.name": "Название формы занятости",
  "employer": "Работодатель",
  "employer.id": "ID работодателя",
  "employer.name": "Название работодателя",
  "employer.url": "Ссылка API работодателя",
  "employer.alternate_url": "Ссылка на работодателя на HH.RU",
  "employer.vacancies_url": "Ссылка на вакансии работодателя",
  "employer.logo_urls": "Логотип работодателя",
  "employer.logo_urls.90": "Логотип 90 пикселей",
  "employer.logo_urls.240": "Логотип 240 пикселей",
  "employer.logo_urls.original": "Оригинал логотипа",
  "employer.trusted": "Проверенный работодатель",
  "employer.accredited_it_employer": "Аккредитованная ИТ-компания",
  "employer.employer_on_additional_check": "Работодатель на дополнительной проверке",
  "apply_alternate_url": "Ссылка для отклика на HH.RU",
  "billing_type": "Тип оплаты",
  "billing_type.id": "Код типа оплаты",
  "billing_type.name": "Название типа оплаты",
  "url": "Ссылка API вакансии",
  "alternate_url": "Ссылка на вакансию на HH.RU",
  "relations": "Связи вакансии",
  "department": "Подразделение",
  "area": "Регион",
  "area.id": "Код региона",
  "area.name": "Название региона",
  "area.url": "Ссылка API региона",
  "address": "Адрес",
  "address.id": "ID адреса",
  "address.city": "Город",
  "address.street": "Улица",
  "address.building": "Дом",
  "address.description": "Описание адреса",
  "address.raw": "Полный адрес",
  "address.lat": "Широта",
  "address.lng": "Долгота",
  "address.metro": "Ближайшее метро",
  "address.metro_stations": "Станции метро",
  "published_at": "Дата публикации",
  "created_at": "Дата создания",
  "counters": "Счётчики",
  "counters.views": "Просмотры",
  "counters.responses": "Отклики",
  "counters.unread_responses": "Непрочитанные отклики",
  "counters.invitations": "Приглашения",
  "counters.invitations_and_responses": "Приглашения и отклики",
  "counters.resumes_in_progress": "Резюме в работе",
  "has_updates": "Есть обновления",
  "has_new_messages": "Есть новые сообщения",
  "manager": "Менеджер",
  "manager.id": "ID менеджера",
  "manager.first_name": "Имя менеджера",
  "manager.middle_name": "Отчество менеджера",
  "manager.last_name": "Фамилия менеджера",
  "closed_for_applicants": "Закрыта для соискателей",
  "vacancy_properties": "Свойства вакансии",
  "vacancy_properties.appearance": "Оформление вакансии",
  "vacancy_properties.appearance.title": "Заголовок оформления",
  "vacancy_properties.properties": "Дополнительные свойства",
  "vacancy_properties.properties[].property_type": "Тип свойства",
  "vacancy_properties.properties[].parameters": "Параметры свойства",
  "vacancy_properties.properties[].start_time": "Время начала",
  "vacancy_properties.properties[].end_time": "Время окончания",
  "ai_assistant": "ИИ-ассистент",
  "ai_assistant.can_apply_ai_assistant": "Можно подключить ИИ-ассистента",
  "ai_assistant.has_ever_been_enabled": "ИИ-ассистент подключался ранее",
  "ai_assistant.is_currently_enabled": "ИИ-ассистент включён",
};
